USE MASTER
IF DB_ID('WHISKEYDB') IS NOT NULL
BEGIN
	DROP TABLE WHISKEY
END



CREATE DATABASE WHISKEYDB
GO
USE WHISKEYDB
GO

CREATE TABLE WHISKEY (
Id INT IDENTITY(1,1),
[Name] NVARCHAR(30),
Region INT,
[Type] INT,
Price DECIMAL
)
SET IDENTITY_INSERT WHISKEY OFF
DROP TABLE WHISKEY

CREATE TABLE MUSIC (
Id INT IDENTITY(1,1),
FavArtist VARCHAR(20),
FavGenre VARCHAR(20),
MostListenedSong VARCHAR(20),
SongRecommendation VARCHAR(20)
)

DELETE FROM Whiskey WHERE Name = 'Glenn Scotia';

DROP TABLE IF EXISTS WHISKEYTYPE
CREATE TABLE WHISKEYTYPE(
Id INT IDENTITY (1,1),
[Type] NVARCHAR(32)
)



INSERT INTO WHISKEYTYPE ([Type]) VALUES ('Blandet')
INSERT INTO WHISKEYTYPE ([Type]) VALUES ('Single Malt')
INSERT INTO WHISKEYTYPE ([Type]) VALUES ('Single Cask')



DROP TABLE IF EXISTS WHISKEYREGION
CREATE TABLE WHISKEYREGION(
Id INT IDENTITY (1,1),
Region NVARCHAR(32)
)

INSERT INTO WHISKEYREGION (Region) VALUES ('Islay')
INSERT INTO WHISKEYREGION (Region) VALUES ('Highland')
INSERT INTO WHISKEYREGION (Region) VALUES ('Speyside')

SELECT [Name], WHISKEYREGION.Region, WHISKEYTYPE.[Type], Price 
FROM WHISKEY, WHISKEYTYPE, WHISKEYREGION 
WHERE WHISKEY.[Type] = WHISKEYTYPE.Id AND WHISKEY.Region = WHISKEYREGION.Id


INSERT INTO WHISKEY ([Name], [Region], [Type]) VALUES ('Glenn Scotia', 1, 1) 
INSERT INTO WHISKEY ([Name], [Region], [Type]) VALUES ('Highland Park', 2, 1) 
INSERT INTO WHISKEY ([Name], [Region], [Type]) VALUES ('Skye', 3, 2) 



SELECT * FROM WHISKEY WHERE [Type] like '%Blandet%'

SELECT COUNT (Id) as Number, [Type] as 'Whiskey Type'  FROM Whiskey GROUP BY [Type]

SELECT STRING_AGG([Name], ' , ') as Names, [Type] as 'Whiskey Type'  FROM Whiskey GROUP BY [Type]

--SELECT DISTINCT Region, [Name] FROM WHISKEY

--SELECT TOP 1 * FROM WHISKEY WHERE [Type] like 'Blandet'

UPDATE WHISKEY
SET Region = 'Higlander'
WHERE Region like '%Highland%';

UPDATE WHISKEY
SET Price = 0

